name: fetch-btc
version: git
summary: Command line bitcoin price tool.
description: description
grade: devel
confinement: devmode

apps:
  fetchb-btc:
    command: bin/fetch-btc

parts:
  fetch-btc:
    plugin: nodejs
    source: .
