name: fetch-btc  # you probably want to 'snapcraft register <name>'
version: '1.2+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: BTC price fetcher # 79 char long summary
description: |
  A Node application fetching and printing the current BTC price in USD, GBP and EUR

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  fetch-btc:
    command: bin/fetch-btc
    plugs: [network]

parts:
  mypart:
    plugin: dump
    prime:
        - bin/*
  fetch-btc:
    after: [mypart]
    # See 'snapcraft plugins'
    plugin: nodejs
    source: .
