name: fetch-btc # you probably want to 'snapcraft register <name>'
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: CLI Application fetching current Bitcoin price # 79 char long summary
description: |
  This is a Node.js CLI application that fetches (and prints) current USD, GBP and EUR Bitcoin price

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  fetch-btc:
    # See 'snapcraft plugins'
    plugin: nodejs
    source: https://github.com/Pl4gue/fetch-btc.git
